import { useQuery } from "@tanstack/react-query";
import { useParams } from "wouter";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Shield, Calendar, User, MapPin, AlertTriangle } from "lucide-react";

export default function IssueReportPage() {
  const params = useParams<{ issueId: string }>();

  const { data: report, isLoading, error } = useQuery<any>({
    queryKey: ["/api/public/issue-report", params.issueId],
    queryFn: async () => {
      const res = await fetch(`/api/public/issue-report/${params.issueId}`);
      if (!res.ok) throw new Error("Report not found");
      return res.json();
    },
  });

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="text-center space-y-2">
          <Shield className="h-12 w-12 text-muted-foreground mx-auto animate-pulse" />
          <p className="text-muted-foreground">Loading report...</p>
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Card className="max-w-md w-full mx-4">
          <CardContent className="pt-6 text-center space-y-3">
            <AlertTriangle className="h-12 w-12 text-destructive mx-auto" />
            <p className="text-lg font-semibold">Report Not Found</p>
            <p className="text-sm text-muted-foreground">
              This report may not exist or has not been generated yet.
            </p>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background py-8">
      <div className="max-w-3xl mx-auto px-4 space-y-6">
        <div className="flex items-center gap-3">
          <Shield className="h-8 w-8 text-primary" />
          <div>
            <h1 className="text-2xl font-bold">Non-Conformance Report</h1>
            <p className="text-sm text-muted-foreground">GuardTrack Incident Management</p>
          </div>
        </div>

        <Card>
          <CardHeader>
            <div className="flex items-start justify-between flex-wrap gap-2">
              <div>
                <p className="text-xs text-muted-foreground font-mono">{report.issueId}</p>
                <CardTitle className="text-xl mt-1">{report.title}</CardTitle>
              </div>
              <Badge variant={report.status === 'Closed' || report.status === 'Resolved' ? 'outline' : 'default'}>
                {report.status}
              </Badge>
            </div>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="grid grid-cols-2 gap-3 text-sm">
              {report.siteName && (
                <div className="flex items-center gap-2 text-muted-foreground">
                  <MapPin className="h-4 w-4 flex-shrink-0" />
                  <span>{report.siteName}</span>
                </div>
              )}
              {report.dateLogged && (
                <div className="flex items-center gap-2 text-muted-foreground">
                  <Calendar className="h-4 w-4 flex-shrink-0" />
                  <span>{new Date(report.dateLogged).toLocaleDateString('en-GB')}</span>
                </div>
              )}
              {report.reportedBy && (
                <div className="flex items-center gap-2 text-muted-foreground">
                  <User className="h-4 w-4 flex-shrink-0" />
                  <span>Reported by {report.reportedBy}</span>
                </div>
              )}
              {report.reportGeneratedAt && (
                <div className="flex items-center gap-2 text-muted-foreground">
                  <Calendar className="h-4 w-4 flex-shrink-0" />
                  <span>Generated {new Date(report.reportGeneratedAt).toLocaleDateString('en-GB')}</span>
                </div>
              )}
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="pt-6">
            <div className="prose prose-sm max-w-none dark:prose-invert whitespace-pre-wrap text-sm leading-relaxed">
              {report.reportContent}
            </div>
          </CardContent>
        </Card>

        <p className="text-center text-xs text-muted-foreground pb-4">
          Generated by GuardTrack Incident Management System
        </p>
      </div>
    </div>
  );
}
